local L0_0, L1_1
L0_0 = "ASSETS/Characters/Leona/HUD/Icons2D/LeonaSunlight.dds"
BuffTextureName = L0_0
L0_0 = "LeonaSunlightPassive"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
