local L0_0, L1_1
L0_0 = "RengarQ.dds"
BuffTextureName = L0_0
L0_0 = "RengarQBuff"
BuffName = L0_0
L0_0 = "Talon_Base_Q_Hit_Ready.troy"
AutoBuffActivateEffect = L0_0
L0_0 = "R_Hand"
AutoBuffActivateAttachBoneName = L0_0
L0_0 = "Talon_Base_Q_Hit_Ready.troy"
AutoBuffActivateEffect2 = L0_0
L0_0 = "L_Hand"
AutoBuffActivateAttachBoneName2 = L0_0
