local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Brand/HUD/Icons2D/BrandP-Debuff.dds"
BuffTextureName = L0_0
L0_0 = "BrandAblazeDetonateMarker"
BuffName = L0_0
L0_0 = true
IsDeathRecapSource = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
