local L0_0
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = true
DoesntBreakShields = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = true
CastingBreaksStealth = L0_0
L0_0 = "Yeti_Shatter.dds"
BuffTextureName = L0_0
L0_0 = "Absolute Zero"
BuffName = L0_0
L0_0 = {"NunuBot"}
SpellFXOverrideSkins = L0_0
L0_0 = {""}
SpellVOOverrideSkins = L0_0
L0_0 = true
IsDamagingSpell = L0_0
