local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Fiora/HUD/Icons2D/Fiora_E.dds"
BuffTextureName = L0_0
L0_0 = "FioraESlow"
BuffName = L0_0
L0_0 = "game_floatingtext_Slowed"
PopupMessage1 = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
