local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = true
CastingBreaksStealth = L0_0
L0_0 = "ASSETS/Characters/Neeko/HUD/Icons2D/Neeko_P.dds"
BuffTextureName = L0_0
L0_0 = "NeekoPassiveBuff"
BuffName = L0_0
