local L0_0, L1_1
L0_0 = "ASSETS/Characters/Morgana/HUD/Icons2D/FallenAngel_Empathize.dds"
BuffTextureName = L0_0
L0_0 = "Empathize"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
