local L0_0, L1_1
L0_0 = "ASSETS/Characters/Bard/HUD/Icons2D/Bard_Meeps_Recharging.dds"
BuffTextureName = L0_0
L0_0 = "BardPDisplaySpiritTimer"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
