local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = true
DoesntTriggerSpellCasts = L0_0
L0_0 = "2140_Elixir_of_Wrath.dds"
BuffTextureName = L0_0
L0_0 = "ElixirOfWrath"
BuffName = L0_0
L0_0 = "Global_Item_ElixirOfWrath_Buf.troy"
AutoBuffActivateEffect = L0_0
L0_0 = "C_BUFFBONE_GLB_CHEST_LOC"
AutoBuffActivateAttachBoneName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
