local L0_0, L1_1
L0_0 = "ASSETS/Characters/Corki/HUD/Icons2D/Corki_RapidReload.dds"
BuffTextureName = L0_0
L0_0 = "CorkiLoadUpCD"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
