local L0_0, L1_1
L0_0 = "ASSETS/Characters/Rumble/HUD/Icons2D/Rumble_ScrapShield2.dds"
BuffTextureName = L0_0
L0_0 = "RumbleShieldBuff"
BuffName = L0_0
L0_0 = "r:rumble_W_speed_buf"
AutoBuffActivateEffect = L0_0
L0_0 = "Robot_Root"
AutoBuffActivateAttachBoneName = L0_0
L0_0 = "r:rumble_W_speed_buf_booster"
AutoBuffActivateEffect2 = L0_0
L0_0 = "BUFFBONE_CSTM_BOOSTER"
AutoBuffActivateAttachBoneName2 = L0_0
