local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "Irelia_HitenStyleReady.dds"
BuffTextureName = L0_0
L0_0 = "DravenFuryPassive"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
