local L0_0, L1_1
L0_0 = false
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Ivern/HUD/Icons2D/IvernSmite.dds"
BuffTextureName = L0_0
L0_0 = "IvernW"
BuffName = L0_0
L0_0 = true
IsDamagingSpell = L0_0
