local L0_0, L1_1
L0_0 = true
DoesntBreakShields = L0_0
L0_0 = true
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Urgot/HUD/Icons2D/Urgot_E.dds"
BuffTextureName = L0_0
L0_0 = "UrgotEStun"
BuffName = L0_0
L0_0 = "game_floatingtext_Stunned"
PopupMessage1 = L0_0
