local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = true
DoesntTriggerSpellCasts = L0_0
L0_0 = "2031_Refillable_Potion.dds"
BuffTextureName = L0_0
L0_0 = "ItemCrystalFlask"
BuffName = L0_0
L0_0 = "GLOBAL_Item_HealthPotion.troy"
AutoBuffActivateEffect = L0_0
L0_0 = "Buffbone_Glb_Ground_Loc"
AutoBuffActivateAttachBoneName = L0_0
