local L0_0, L1_1
L0_0 = "ASSETS/Characters/Lucian/HUD/Icons2D/Lucian_Passive.dds"
BuffTextureName = L0_0
L0_0 = "LucianPassiveBuff"
BuffName = L0_0
L0_0 = true
IsDeathRecapSource = L0_0
L0_0 = false
IsDamagingSpell = L0_0
