local L0_0, L1_1
L0_0 = "ASSETS/Characters/Malzahar/HUD/Icons2D/Malzahar_Passive.dds"
BuffTextureName = L0_0
L0_0 = "MalzaharPassive"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
