local L0_0, L1_1
L0_0 = "ASSETS/Characters/Vladimir/HUD/Icons2D/VladimirW.dds"
BuffTextureName = L0_0
L0_0 = "VladimirSanguinePoolSlow"
BuffName = L0_0
L0_0 = "r:Vladimir_Global_Slow"
AutoBuffActivateEffect = L0_0
L0_0 = "game_floatingtext_Slowed"
PopupMessage1 = L0_0
