local L0_0, L1_1
L0_0 = "ASSETS/Characters/MissFortune/HUD/Icons2D/MissFortune_E.dds"
BuffTextureName = L0_0
L0_0 = "MissFortuneScattershotSlow"
BuffName = L0_0
L0_0 = "GLOBAL_SLOW.TROY"
AutoBuffActivateEffect = L0_0
L0_0 = "game_floatingtext_Slowed"
PopupMessage1 = L0_0
