local L0_0, L1_1
L0_0 = "ASSETS/Characters/Shaco/HUD/Icons2D/Jester_CarefulStrikes.dds"
BuffTextureName = L0_0
L0_0 = "Backstab"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
