local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = true
DoesntTriggerSpellCasts = L0_0
L0_0 = "2033_Corrupted_Potion.dds"
BuffTextureName = L0_0
L0_0 = "ItemDarkCrystalFlask"
BuffName = L0_0
L0_0 = "Global_Item_DarkCrystalFlask.troy"
AutoBuffActivateEffect = L0_0
L0_0 = "Buffbone_Glb_Ground_Loc"
AutoBuffActivateAttachBoneName = L0_0
