local L0_0, L1_1
L0_0 = "ASSETS/Characters/Urgot/HUD/Icons2D/Urgot_R.dds"
BuffTextureName = L0_0
L0_0 = "UrgotRSlow"
BuffName = L0_0
L0_0 = "GLOBAL_SLOW.TROY"
AutoBuffActivateEffect = L0_0
L0_0 = "game_floatingtext_Slowed"
PopupMessage1 = L0_0
