local L0_0, L1_1
L0_0 = false
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntBreakShields = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = false
CastingBreaksStealth = L0_0
L0_0 = "ASSETS/Characters/Jinx/HUD/Icons2D/Jinx_E.dds"
BuffTextureName = L0_0
L0_0 = "JinxEMineSnare"
BuffName = L0_0
L0_0 = "game_floatingtext_Snared"
PopupMessage1 = L0_0
L0_0 = true
IsDamagingSpell = L0_0
