local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Volibear/HUD/Icons2D/DrMundo_Masochism.dds"
BuffTextureName = L0_0
L0_0 = "VolibearWBuff"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
TriggersSpellCasts = L0_0
