local L0_0, L1_1
L0_0 = "ASSETS/Characters/Nidalee/HUD/Icons2D/Nidalee_Passive.dds"
BuffTextureName = L0_0
L0_0 = "Prowl"
BuffName = L0_0
L0_0 = "r:Nidalee_P"
AutoBuffActivateEffect = L0_0
L0_0 = "BUFFBONE_GLB_GROUND_LOC"
AutoBuffActivateAttachBoneName = L0_0
