local L0_0, L1_1
L0_0 = false
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "Averdrian_AstralBeam.dds"
BuffTextureName = L0_0
L0_0 = "NullLance"
BuffName = L0_0
L0_0 = "Null_Lance_buf.troy"
AutoBuffActivateEffect = L0_0
L0_0 = true
IsDamagingSpell = L0_0
