local L0_0, L1_1
L0_0 = "ASSETS/Characters/Blitzcrank/HUD/Icons2D/Blitzcrank_ManaBarrierCD.dds"
BuffTextureName = L0_0
L0_0 = "BlitzcrankManaBarrierCD"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
