local L0_0, L1_1
L0_0 = "ASSETS/Characters/Vayne/HUD/Icons2D/Vayne_Tumble.dds"
BuffTextureName = L0_0
L0_0 = "VayneTumble"
BuffName = L0_0
L0_0 = "r:Vayne_Q_buf"
AutoBuffActivateEffect = L0_0
L0_0 = "l_hand"
AutoBuffActivateAttachBoneName = L0_0
L0_0 = "r:Vayne_Q_buf"
AutoBuffActivateEffect2 = L0_0
L0_0 = "r_hand"
AutoBuffActivateAttachBoneName2 = L0_0
L0_0 = "r:Vayne_Q_cas"
AutoBuffActivateEffect3 = L0_0
