local L0_0, L1_1
L0_0 = "ASSETS/Characters/Khazix/HUD/Icons2D/Khazix_RengarHunt.dds"
BuffTextureName = L0_0
L0_0 = "KhazixHunt"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
