local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = true
DoesntBreakShields = L0_0
L0_0 = true
DoesntTriggerSpellCasts = L0_0
L0_0 = true
CastingBreaksStealth = L0_0
L0_0 = "ASSETS/Characters/Yasuo/HUD/Icons2D/Yasuo_E.dds"
BuffTextureName = L0_0
L0_0 = "YasuoDashWrapperChaos"
BuffName = L0_0
L0_0 = true
IsDamagingSpell = L0_0
