local L0_0, L1_1
L0_0 = false
NotSingleTargetSpell = L0_0
L0_0 = true
DoesntBreakShields = L0_0
L0_0 = false
CastingBreaksStealth = L0_0
L0_0 = "ASSETS/Characters/Anivia/HUD/Icons2D/Evelynn_ReadyToBetray.dds"
BuffTextureName = L0_0
L0_0 = "ShadowMark"
BuffName = L0_0
L0_0 = true
TriggersSpellCasts = L0_0
