local L0_0, L1_1
L0_0 = "ASSETS/Characters/Xerath/HUD/Icons2D/Xerath_AscendedForm.dds"
BuffTextureName = L0_0
L0_0 = "XerathAscended2"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
Nondispellable = L0_0
