local L0_0, L1_1
L0_0 = false
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntBreakShields = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = true
CastingBreaksStealth = L0_0
L0_0 = "ASSETS/Characters/Camille/HUD/Icons2D/Camille_W.dds"
BuffTextureName = L0_0
L0_0 = "CamilleWConeSlashCharge"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
IsDamagingSpell = L0_0
