local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = true
CastingBreaksStealth = L0_0
L0_0 = "ASSETS/Characters/MonkeyKing/HUD/Icons2D/MonkeyKingCyclone.dds"
BuffTextureName = L0_0
L0_0 = "MonkeyKingSpinToWin"
BuffName = L0_0
L0_0 = true
TriggersSpellCasts = L0_0
