local L0_0, L1_1
L0_0 = "ASSETS/Characters/Mordekaiser/HUD/Icons2D/MordekaiserRDragon.dds"
BuffTextureName = L0_0
L0_0 = "MordekaiserChildrenOfTheGravePetBuff"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
IsPetDurationBuff = L0_0
