local L0_0, L1_1
L0_0 = "Jester_Paranoia.dds"
BuffTextureName = L0_0
L0_0 = "EvelynnDisperseShadows"
BuffName = L0_0
L0_0 = "Nearsight_glb.troy"
AutoBuffActivateEffect = L0_0
L0_0 = "root"
AutoBuffActivateAttachBoneName = L0_0
