local L0_0, L1_1
L0_0 = "ASSETS/Characters/Aatrox/HUD/Icons2D/Aatrox_R.dds"
BuffTextureName = L0_0
L0_0 = "AatroxRRevive"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
