local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "Smite_Blue.dds"
BuffTextureName = L0_0
L0_0 = "ItemChillingSmiteSpeed"
BuffName = L0_0
L0_0 = "Boots_Deathmarch.troy"
AutoBuffActivateEffect = L0_0
