local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = true
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Warwick/HUD/Icons2D/Wolfman_FrenziedStrikes.dds"
BuffTextureName = L0_0
L0_0 = "WarwickWHuntersMarkPackMember"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
