local L0_0, L1_1
L0_0 = false
NotSingleTargetSpell = L0_0
L0_0 = true
DoesntBreakShields = L0_0
L0_0 = true
DoesntTriggerSpellCasts = L0_0
L0_0 = false
CastingBreaksStealth = L0_0
L0_0 = "ASSETS/Spells/Icons2D/Minotaur_Pulverize.dds"
BuffTextureName = L0_0
L0_0 = "VolibearRApplicator"
BuffName = L0_0
L0_0 = true
IsDamagingSpell = L0_0
