local L0_0, L1_1
L0_0 = false
NotSingleTargetSpell = L0_0
L0_0 = true
DoesntBreakShields = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = true
CastingBreaksStealth = L0_0
L0_0 = "ASSETS/Characters/Evelynn/HUD/Icons2D/Evelynn_Ravage.dds"
BuffTextureName = L0_0
L0_0 = "EvelynnR"
BuffName = L0_0
L0_0 = true
IsDamagingSpell = L0_0
