local L0_0, L1_1
L0_0 = "SylasR.dds"
BuffTextureName = L0_0
L0_0 = "SylasRBuff"
BuffName = L0_0
L0_0 = "L_Buffbone_Glb_Hand_Loc"
AutoBuffActivateAttachBoneName = L0_0
L0_0 = "R_Buffbone_Glb_Hand_Loc"
AutoBuffActivateAttachBoneName2 = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
