local L0_0, L1_1
L0_0 = "ASSETS/Characters/Rumble/HUD/Icons2D/Rumble_ElectroHarpoon.dds"
BuffTextureName = L0_0
L0_0 = "RumbleGrenadeSlow"
BuffName = L0_0
L0_0 = "Global_Slow.troy"
AutoBuffActivateEffect = L0_0
L0_0 = "game_floatingtext_Slowed"
PopupMessage1 = L0_0
