local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = true
DoesntBreakShields = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = true
CastingBreaksStealth = L0_0
L0_0 = "ASSETS/Characters/AurelionSol/HUD/Icons2D/AurelionSol_Q.dds"
BuffTextureName = L0_0
L0_0 = "AurelionSolQ"
BuffName = L0_0
L0_0 = true
IsDamagingSpell = L0_0
