local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = true
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Tristana/HUD/Icons2D/Tristana_Passive.dds"
BuffTextureName = L0_0
L0_0 = "TristanaPassive"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
L0_0 = false
TriggersSpellCasts = L0_0
