local L0_0, L1_1
L0_0 = false
NotSingleTargetSpell = L0_0
L0_0 = true
DoesntBreakShields = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = true
CastingBreaksStealth = L0_0
L0_0 = "ASSETS/Perks/Styles/Domination/Predator/Predator.dds"
BuffTextureName = L0_0
L0_0 = "ZoeW_IconItemBloodMoonBootsActive"
BuffName = L0_0
L0_0 = 1
SpellToggleSlot = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
