local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = true
CastingBreaksStealth = L0_0
L0_0 = "ASSETS/Characters/Twitch/HUD/Icons2D/Twitch_Q.dds"
BuffTextureName = L0_0
L0_0 = "TwitchHideInShadows"
BuffName = L0_0
L0_0 = false
IsDamagingSpell = L0_0
