local L0_0, L1_1
L0_0 = false
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Elise/HUD/Icons2D/EliseHumanE.dds"
BuffTextureName = L0_0
L0_0 = "EliseHumanEHeal"
BuffName = L0_0
L0_0 = true
IsDamagingSpell = L0_0
