local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = true
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Garen/HUD/Icons2D/Garen_W.dds"
BuffTextureName = L0_0
L0_0 = "GarenWPassive"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
