local L0_0, L1_1
L0_0 = "ASSETS/Characters/Bard/HUD/Icons2D/Bard_Passive_RequiredForNext.dds"
BuffTextureName = L0_0
L0_0 = "BardPDisplayRequiredChimes"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
