local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "Shen_Feint.dds"
BuffTextureName = L0_0
L0_0 = "ItemSmiteShield"
BuffName = L0_0
L0_0 = "Global_SS_Smite_Duel_Shield.troy"
AutoBuffActivateEffect = L0_0
L0_0 = "C_BUFFBONE_GLB_CHEST_LOC"
AutoBuffActivateAttachBoneName = L0_0
