local L0_0, L1_1
L0_0 = false
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Renekton/HUD/Icons2D/Renekton_E2.dds"
BuffTextureName = L0_0
L0_0 = "RenektonSliceAndDiceShred"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
