local L0_0, L1_1
L0_0 = false
NotSingleTargetSpell = L0_0
L0_0 = true
DoesntBreakShields = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = true
CastingBreaksStealth = L0_0
L0_0 = "ASSETS/Characters/Maokai/HUD/Icons2D/Maokai_R.dds"
BuffTextureName = L0_0
L0_0 = "MaokaiRSoundMis"
BuffName = L0_0
L0_0 = true
IsDamagingSpell = L0_0
