local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = true
DoesntTriggerSpellCasts = L0_0
L0_0 = "Summoner_haste.dds"
BuffTextureName = L0_0
L0_0 = "Haste"
BuffName = L0_0
L0_0 = "Global_SS_Ghost.troy"
AutoBuffActivateEffect = L0_0
