local L0_0, L1_1
L0_0 = "ASSETS/Characters/Zilean/HUD/Icons2D/Zilean_E.dds"
BuffTextureName = L0_0
L0_0 = "Slow"
BuffName = L0_0
L0_0 = "global_slow.troy"
AutoBuffActivateEffect2 = L0_0
L0_0 = "game_floatingtext_Slowed"
PopupMessage1 = L0_0
