local L0_0, L1_1
L0_0 = false
DoesntBreakShields = L0_0
L0_0 = true
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Lux/HUD/Icons2D/LuxIlluminatingFraulein.dds"
BuffTextureName = L0_0
L0_0 = "LuxIlluminationPassive"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
