local L0_0, L1_1
L0_0 = "ThreeSisters_WintersClaw.dds"
BuffTextureName = L0_0
L0_0 = "ThreeSistersSejuaniDefeatedLissandra"
BuffName = L0_0
L0_0 = "Freljord_Crown_Sejuani.troy"
AutoBuffActivateEffect = L0_0
L0_0 = "C_Buffbone_Glb_Overhead_Loc"
AutoBuffActivateAttachBoneName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
