local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "ItemJungleGoldPenalty.dds"
BuffTextureName = L0_0
L0_0 = "ItemJungleGoldPenalty"
BuffName = L0_0
L0_0 = "ItemJungleGoldPenalty"
DisplayName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
