local L0_0, L1_1
L0_0 = "ASSETS/Characters/Blitzcrank/HUD/Icons2D/Blitzcrank_ManaBarrier.dds"
BuffTextureName = L0_0
L0_0 = "ManaBarrierIcon"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
L0_0 = 8
OnPreDamagePriority = L0_0
