local L0_0, L1_1
L0_0 = "ASSETS/Characters/Nasus/HUD/Icons2D/Sion_SpiritFeast.dds"
BuffTextureName = L0_0
L0_0 = "CannibalismMaxHPGained"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
