local L0_0, L1_1
L0_0 = "ASSETS/Characters/Twitch/HUD/Icons2D/Twitch_DeadlyVenom_temp.dds"
BuffTextureName = L0_0
L0_0 = "TwitchDeadlyVenomMarker"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
