local L0_0, L1_1
L0_0 = false
NotSingleTargetSpell = L0_0
L0_0 = true
DoesntTriggerSpellCasts = L0_0
L0_0 = "Ezreal_EssenceFlux.dds"
BuffTextureName = L0_0
L0_0 = "EzrealEssenceFluxDebuff"
BuffName = L0_0
L0_0 = "GLOBAL_SLOW.troy"
AutoBuffActivateEffect = L0_0
L0_0 = true
IsDamagingSpell = L0_0
L0_0 = true
TriggersSpellCasts = L0_0
