local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = true
DoesntTriggerSpellCasts = L0_0
L0_0 = "OdinTrinketRevive"
BuffName = L0_0
L0_0 = "global_ss_revive.troy"
AutoBuffActivateEffect = L0_0
