local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = true
DoesntBreakShields = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Cassiopeia/HUD/Icons2D/Cassiopeia_Q.dds"
BuffTextureName = L0_0
L0_0 = "CassiopeiaQ"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
IsDamagingSpell = L0_0
