local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Jax/HUD/Icons2D/Armsmaster_Empower.dds"
BuffTextureName = L0_0
L0_0 = "EmpowerTwo"
BuffName = L0_0
