local L0_0, L1_1
L0_0 = "ASSETS/Characters/Garen/HUD/Icons2D/Garen_PerseveranceCD.dds"
BuffTextureName = L0_0
L0_0 = "GarenPassiveCooldown"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
