local L0_0, L1_1
L0_0 = "ASSETS/Characters/Draven/HUD/Icons2D/Draven_passive.dds"
BuffTextureName = L0_0
L0_0 = "DravenPassiveStacks"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
