local L0_0, L1_1
L0_0 = "GSB_stun.dds"
BuffTextureName = L0_0
L0_0 = "Stun"
BuffName = L0_0
L0_0 = "LOC_Stun.troy"
AutoBuffActivateEffect = L0_0
L0_0 = "C_BUFFBONE_GLB_CENTER_LOC"
AutoBuffActivateAttachBoneName = L0_0
L0_0 = "game_floatingtext_Stunned"
PopupMessage1 = L0_0
