local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = false
CastingBreaksStealth = L0_0
L0_0 = "ASSETS/Characters/Orianna/HUD/Icons2D/OriannaPowerDagger.dds"
BuffTextureName = L0_0
L0_0 = "OriannaPStack"
BuffName = L0_0
