local L0_0, L1_1
L0_0 = "ASSETS/Characters/Malphite/HUD/Icons2D/Malphite_GraniteShield.dds"
BuffTextureName = L0_0
L0_0 = "MalphiteShield"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
