local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Tryndamere/HUD/Icons2D/Tryndamere_W.dds"
BuffTextureName = L0_0
L0_0 = "TryndamereW"
BuffName = L0_0
