local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = true
DoesntTriggerSpellCasts = L0_0
L0_0 = "2139_Elixir_of_Sorcery.dds"
BuffTextureName = L0_0
L0_0 = "ElixirOfSorcery"
BuffName = L0_0
L0_0 = "Global_Item_ElixirOfSorcery_Buf.troy"
AutoBuffActivateEffect = L0_0
L0_0 = "C_BUFFBONE_GLB_CHEST_LOC"
AutoBuffActivateAttachBoneName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
