local L0_0, L1_1
L0_0 = true
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Thresh/HUD/Icons2D/Thresh_Passive.dds"
BuffTextureName = L0_0
L0_0 = "ThreshPassiveSoulsGain"
BuffName = L0_0
L0_0 = true
IsDeathRecapSource = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
