local L0_0, L1_1
L0_0 = false
NotSingleTargetSpell = L0_0
L0_0 = true
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/TwistedFate/HUD/Icons2D/Cardmaster_RapidToss.dds"
BuffTextureName = L0_0
L0_0 = "CardMasterStack"
BuffName = L0_0
L0_0 = 3
SpellToggleSlot = L0_0
L0_0 = true
IsDeathRecapSource = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
