local L0_0, L1_1
L0_0 = false
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Ornn/HUD/Icons2D/OrnnP.dds"
BuffTextureName = L0_0
L0_0 = "OrnnPAllyItemReady"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
IsDamagingSpell = L0_0
