local L0_0, L1_1
L0_0 = "3053_Steraks_Gage.dds"
BuffTextureName = L0_0
L0_0 = "PrimalTalonEnrage"
BuffName = L0_0
L0_0 = "Item_PrimalTalon_Enrage_Buff.troy"
AutoBuffActivateEffect = L0_0
L0_0 = "C_BUFFBONE_GLB_CENTER_LOC"
AutoBuffActivateAttachBoneName = L0_0
