local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = true
DoesntBreakShields = L0_0
L0_0 = true
DoesntTriggerSpellCasts = L0_0
L0_0 = true
CastingBreaksStealth = L0_0
L0_0 = "ASSETS/Characters/Nautilus/HUD/Icons2D/Nautilus_Wrath.dds"
BuffTextureName = L0_0
L0_0 = "NautilusWDoT"
BuffName = L0_0
L0_0 = true
IsDeathRecapSource = L0_0
L0_0 = false
IsDamagingSpell = L0_0
