local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "Smite_Blue.dds"
BuffTextureName = L0_0
L0_0 = "ItemSmiteSlow"
BuffName = L0_0
L0_0 = "Global_SS_Smite_Player_Slow.troy"
AutoBuffActivateEffect = L0_0
