local L0_0, L1_1
L0_0 = "ASSETS/Characters/Sivir/HUD/Icons2D/Sivir_Passive.dds"
BuffTextureName = L0_0
L0_0 = "SivirPassive"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
