local L0_0, L1_1
L0_0 = false
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntBreakShields = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = true
CastingBreaksStealth = L0_0
L0_0 = "ASSETS/Spells/Icons2D/GemKnight_Shatter.dds"
BuffTextureName = L0_0
L0_0 = "MaokaiTrunkSmash"
BuffName = L0_0
L0_0 = true
IsDamagingSpell = L0_0
