local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = true
DoesntBreakShields = L0_0
L0_0 = true
DoesntTriggerSpellCasts = L0_0
L0_0 = "FallenAngel_DarkBinding.dds"
BuffTextureName = L0_0
L0_0 = "XerathLocusOfPower"
BuffName = L0_0
L0_0 = "game_floatingtext_Snared"
PopupMessage1 = L0_0
L0_0 = true
IsDamagingSpell = L0_0
