local L0_0, L1_1
L0_0 = "ASSETS/Characters/Fizz/HUD/Icons2D/Fizz_W.dds"
BuffTextureName = L0_0
L0_0 = "FizzOnHitBuff"
BuffName = L0_0
L0_0 = "r:Fizz_W_Weapon"
AutoBuffActivateEffect = L0_0
L0_0 = "BUFFBONE_CSTM_WEAPON_1"
AutoBuffActivateAttachBoneName = L0_0
