local L0_0, L1_1
L0_0 = "ASSETS/Characters/MissFortune/HUD/Icons2D/IsPirate.dds"
BuffTextureName = L0_0
L0_0 = "IsPirateHunter"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
Nondispellable = L0_0
