local L0_0, L1_1
L0_0 = false
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Karma/HUD/Icons2D/Karma_W1.dds"
BuffTextureName = L0_0
L0_0 = "KarmaSpiritBindRoot"
BuffName = L0_0
L0_0 = "global_Watched.troy"
AutoBuffActivateEffect = L0_0
L0_0 = "C_BUFFBONE_GLB_HEAD_LOC"
AutoBuffActivateAttachBoneName = L0_0
L0_0 = "game_floatingtext_Snared"
PopupMessage1 = L0_0
L0_0 = true
IsDamagingSpell = L0_0
