local L0_0, L1_1
L0_0 = "ASSETS/Characters/Corki/HUD/Icons2D/Corki_R_BigOne.dds"
BuffTextureName = L0_0
L0_0 = "CorkiMissileBarrageCounterBig"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
