local L0_0, L1_1
L0_0 = false
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "IvernW"
BuffName = L0_0
L0_0 = "LOC_Stun.troy"
AutoBuffActivateEffect = L0_0
L0_0 = "C_Buffbone_Glb_Overhead_Loc"
AutoBuffActivateAttachBoneName = L0_0
L0_0 = "game_floatingtext_Stunned"
PopupMessage1 = L0_0
L0_0 = true
IsDamagingSpell = L0_0
