local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = true
DoesntBreakShields = L0_0
L0_0 = true
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Akali/HUD/Icons2D/Akali_E.AkaliUpdate.dds"
BuffTextureName = L0_0
L0_0 = "AkaliE"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
