local L0_0, L1_1
L0_0 = "ASSETS/Characters/Evelynn/HUD/Icons2D/Evelynn_Passive.dds"
BuffTextureName = L0_0
L0_0 = "EvelynnPassive"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
Nondispellable = L0_0
