local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Alistar/HUD/Icons2D/Alistar_E_Cooldown.dds"
BuffTextureName = L0_0
L0_0 = "AlistarE"
BuffName = L0_0
L0_0 = true
IsDeathRecapSource = L0_0
