local L0_0, L1_1
L0_0 = "Odin_SpeedShrine.dds"
BuffTextureName = L0_0
L0_0 = "TT_SpeedShrine_Buff"
BuffName = L0_0
L0_0 = "tt_speedshrine_buf.troy"
AutoBuffActivateEffect = L0_0
L0_0 = true
NonDispellable = L0_0
