local L0_0, L1_1
L0_0 = "ASSETS/Characters/Darius/HUD/Icons2D/Darius_Icon_Hemorrhage.dds"
BuffTextureName = L0_0
L0_0 = "DariusHemoMarker"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
