local L0_0, L1_1
L0_0 = true
DoesntBreakShields = L0_0
L0_0 = true
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Urgot/HUD/Icons2D/Urgot_R.dds"
BuffTextureName = L0_0
L0_0 = "UrgotRFear"
BuffName = L0_0
