local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "Buff_Devourer.dds"
BuffTextureName = L0_0
L0_0 = "Enchantment_Slayer_Stacks"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
