local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = true
DoesntTriggerSpellCasts = L0_0
L0_0 = "RelicBlueWard.dds"
BuffTextureName = L0_0
L0_0 = "RelicBlueWard"
BuffName = L0_0
L0_0 = "Ward_Blue_Idle.troy"
AutoBuffActivateEffect = L0_0
