local L0_0, L1_1
L0_0 = false
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Nami/HUD/Icons2D/NamiE.dds"
BuffTextureName = L0_0
L0_0 = "NamiESlowtt"
BuffName = L0_0
L0_0 = "Global_Slow.troy"
AutoBuffActivateEffect = L0_0
L0_0 = "game_floatingtext_Slowed"
PopupMessage1 = L0_0
L0_0 = true
IsDamagingSpell = L0_0
