local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Katarina/HUD/Icons2D/Katarina_W.dds"
BuffTextureName = L0_0
L0_0 = "KatarinaW"
BuffName = L0_0
