local L0_0, L1_1
L0_0 = "ASSETS/Characters/Nautilus/HUD/Icons2D/Nautilus_StaggeringBlow.dds"
BuffTextureName = L0_0
L0_0 = "NautilusPassiveCheck"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
