local L0_0, L1_1
L0_0 = false
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Thresh/HUD/Icons2D/Thresh_W.dds"
BuffTextureName = L0_0
L0_0 = "ThreshWShield"
BuffName = L0_0
L0_0 = 3
OnPreDamagePriority = L0_0
L0_0 = true
IsDamagingSpell = L0_0
L0_0 = true
DoOnPreDamageInExpirationOrder = L0_0
L0_0 = "DeathsCaress_buf.troy"
AutoBuffActivateEvent = L0_0
