local L0_0, L1_1
L0_0 = "Crab_Circle_0.dds"
BuffTextureName = L0_0
L0_0 = "Sru_CrabSpeedBoost"
BuffName = L0_0
L0_0 = "r:SRU_Crab_Z_Speed_buff"
AutoBuffActivateEffect = L0_0
L0_0 = "r:SRU_Crab_Z_SpeedBoost_Audio"
AutoBuffActivateEffect2 = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
