local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = true
DoesntTriggerSpellCasts = L0_0
L0_0 = false
CastingBreaksStealth = L0_0
L0_0 = "ASSETS/Characters/Shaco/HUD/Icons2D/Jester_HallucinogenBomb.dds"
BuffTextureName = L0_0
L0_0 = "Hallucinate"
BuffName = L0_0
L0_0 = false
IsDamagingSpell = L0_0
L0_0 = true
IsPetDurationBuff = L0_0
