local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Sivir/HUD/Icons2D/Sivir_E.dds"
BuffTextureName = L0_0
L0_0 = "YuumiE"
BuffName = L0_0
