local L0_0, L1_1
L0_0 = "ASSETS/Characters/Sejuani/HUD/Icons2D/Sejuani_R.dds"
BuffTextureName = L0_0
L0_0 = "Slow"
BuffName = L0_0
L0_0 = "Global_Freeze.troy"
AutoBuffActivateEffect = L0_0
L0_0 = "game_floatingtext_Slowed"
PopupMessage1 = L0_0
