local L0_0, L1_1
L0_0 = "r:Skarner_Q_Buf"
AutoBuffActivateEffect = L0_0
L0_0 = "L_crystals"
AutoBuffActivateAttachBoneName = L0_0
L0_0 = "r:Skarner_Q_Buf"
AutoBuffActivateEffect2 = L0_0
L0_0 = "R_crystals"
AutoBuffActivateAttachBoneName2 = L0_0
L0_0 = "r:Skarner_Q_Buf"
AutoBuffActivateEffect3 = L0_0
L0_0 = "tail_t"
AutoBuffActivateAttachBoneName3 = L0_0
