local L0_0, L1_1
L0_0 = "ASSETS/Spells/Icons2D/Cardmaster_RapidToss.dds"
BuffTextureName = L0_0
L0_0 = "TFT_FizzQProtection"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
