local L0_0, L1_1
L0_0 = false
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = true
CastingBreaksStealth = L0_0
L0_0 = "Evelynn_Ravage.dds"
BuffTextureName = L0_0
L0_0 = "Ravage"
BuffName = L0_0
L0_0 = "RendingShot_buf.troy"
AutoBuffActivateEffect = L0_0
L0_0 = true
IsDamagingSpell = L0_0
