local L0_0, L1_1
L0_0 = false
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Ivern/HUD/Icons2D/IvernQ.dds"
BuffTextureName = L0_0
L0_0 = "IvernQ"
BuffName = L0_0
L0_0 = "game_floatingtext_Snared"
PopupMessage1 = L0_0
L0_0 = true
IsDamagingSpell = L0_0
