local L0_0, L1_1
L0_0 = "ASSETS/Characters/Chogath/HUD/Icons2D/GreenTerror_ChitinousExoplates.dds"
BuffTextureName = L0_0
L0_0 = "VorpalSpikesDebuff"
BuffName = L0_0
L0_0 = "Global_Slow.troy"
AutoBuffActivateEffect = L0_0
L0_0 = "game_floatingtext_Slowed"
PopupMessage1 = L0_0
