local L0_0, L1_1
L0_0 = "ASSETS/Characters/Karma/HUD/Icons2D/Karma_Q2.dds"
BuffTextureName = L0_0
L0_0 = "KarmaQMissile"
BuffName = L0_0
L0_0 = "GLOBAL_SLOW.TROY"
AutoBuffActivateEffect = L0_0
L0_0 = "Buffbone_Glb_Ground_Loc"
AutoBuffActivateAttachBoneName = L0_0
L0_0 = "game_floatingtext_Slowed"
PopupMessage1 = L0_0
