local L0_0, L1_1
L0_0 = false
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Spells/Icons2D/Chronokeeper_Timestop.dds"
BuffTextureName = L0_0
L0_0 = "Slow"
BuffName = L0_0
L0_0 = "r:Zac_R_slow_tar"
AutoBuffActivateEffect = L0_0
L0_0 = "game_floatingtext_Slowed"
PopupMessage1 = L0_0
L0_0 = true
NonDispellable = L0_0
L0_0 = true
IsDamagingSpell = L0_0
