local L0_0, L1_1
L0_0 = "ASSETS/Characters/Mordekaiser/HUD/Icons2D/MordekaiserPassive.dds"
BuffTextureName = L0_0
L0_0 = "MordekaiserIronMan"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = 3
OnPreDamagePriority = L0_0
