local L0_0, L1_1
L0_0 = "ASSETS/Characters/Kalista/HUD/Icons2D/Kalista_Passive_Item.dds"
BuffTextureName = L0_0
L0_0 = "KalistaPassiveCoopStrike"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
