local L0_0, L1_1
L0_0 = true
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Kaisa/HUD/Icons2D/Kaisa_Passive.dds"
BuffTextureName = L0_0
L0_0 = "KaisaPassiveMarker"
BuffName = L0_0
L0_0 = true
IsDeathRecapSource = L0_0
