local L0_0, L1_1
L0_0 = false
NotSingleTargetSpell = L0_0
L0_0 = true
DoesntBreakShields = L0_0
L0_0 = true
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/AurelionSol/HUD/Icons2D/AurelionSol_Q.dds"
BuffTextureName = L0_0
L0_0 = "AurelionSolQCancelButton"
BuffName = L0_0
