local L0_0, L1_1
L0_0 = "ASSETS/Characters/Kogmaw/HUD/Icons2D/KogMaw_IcathianSurprise.dds"
BuffTextureName = L0_0
L0_0 = "KogMawIcathianSurpriseReady"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
L0_0 = 2
DeathEventType = L0_0
