DoLuaShared("Spawning")
function CreateLevelProps()
  SpawnTurret("Turret_T1_R_03", "SRUAP_Turret_Order1", TEAM_ORDER, 3, 0)
  SpawnTurret("Turret_T1_R_02", "SRUAP_Turret_Order2", TEAM_ORDER, 2, 0)
  SpawnTurret("Turret_T1_C_07", "SRUAP_Turret_Order3", TEAM_ORDER, 1, 0)
  SpawnTurret("Turret_T2_R_03", "SRUAP_Turret_Chaos1", TEAM_CHAOS, 3, 0)
  SpawnTurret("Turret_T2_R_02", "SRUAP_Turret_Chaos2", TEAM_CHAOS, 2, 0)
  SpawnTurret("Turret_T2_R_01", "SRUAP_Turret_Chaos3", TEAM_CHAOS, 1, 0)
  SpawnTurret("Turret_T1_C_05", "SRUAP_Turret_Order1", TEAM_ORDER, 3, 1)
  SpawnTurret("Turret_T1_C_04", "SRUAP_Turret_Order2", TEAM_ORDER, 2, 1)
  SpawnTurret("Turret_T1_C_03", "SRUAP_Turret_Order3", TEAM_ORDER, 1, 1)
  SpawnTurret("Turret_T1_C_01", "SRUAP_Turret_Order4", TEAM_ORDER, 5, 1)
  SpawnTurret("Turret_T1_C_02", "SRUAP_Turret_Order4", TEAM_ORDER, 4, 1)
  SpawnTurret("Turret_T2_C_05", "SRUAP_Turret_Chaos1", TEAM_CHAOS, 3, 1)
  SpawnTurret("Turret_T2_C_04", "SRUAP_Turret_Chaos2", TEAM_CHAOS, 2, 1)
  SpawnTurret("Turret_T2_C_03", "SRUAP_Turret_Chaos3", TEAM_CHAOS, 1, 1)
  SpawnTurret("Turret_T2_C_01", "SRUAP_Turret_Chaos4", TEAM_CHAOS, 5, 1)
  SpawnTurret("Turret_T2_C_02", "SRUAP_Turret_Chaos4", TEAM_CHAOS, 4, 1)
  SpawnTurret("Turret_OrderTurretShrine", "SRUAP_Turret_Order5", TEAM_ORDER, 0, 1)
  SpawnTurret("Turret_ChaosTurretShrine", "SRUAP_MageCrystal", TEAM_CHAOS, 0, 1)
  SpawnTurret("Turret_T1_L_03", "SRUAP_Turret_Order1", TEAM_ORDER, 3, 2)
  SpawnTurret("Turret_T1_L_02", "SRUAP_Turret_Order2", TEAM_ORDER, 2, 2)
  SpawnTurret("Turret_T1_C_06", "SRUAP_Turret_Order3", TEAM_ORDER, 1, 2)
  SpawnTurret("Turret_T2_L_03", "SRUAP_Turret_Chaos1", TEAM_CHAOS, 3, 2)
  SpawnTurret("Turret_T2_L_02", "SRUAP_Turret_Chaos2", TEAM_CHAOS, 2, 2)
  SpawnTurret("Turret_T2_L_01", "SRUAP_Turret_Chaos3", TEAM_CHAOS, 1, 2)
end
