local L0_0, L1_1
L0_0 = "ASSETS/Characters/Corki/HUD/Icons2D/Corki_PhosphorusBomb.dds"
BuffTextureName = L0_0
L0_0 = "PhosphorusBomb"
BuffName = L0_0
L0_0 = "global_Watched.troy"
AutoBuffActivateEffect = L0_0
L0_0 = "C_BUFFBONE_GLB_HEAD_LOC"
AutoBuffActivateAttachBoneName = L0_0
L0_0 = false
IsDamagingSpell = L0_0
