local L0_0, L1_1
L0_0 = false
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Zilean/HUD/Icons2D/Zilean_Q.dds"
BuffTextureName = L0_0
L0_0 = "ZileanQEnemyBomb"
BuffName = L0_0
L0_0 = true
IsDamagingSpell = L0_0
