local L0_0, L1_1
L0_0 = "ASSETS/Characters/Janna/HUD/Icons2D/Janna_Tailwind.dds"
BuffTextureName = L0_0
L0_0 = "TailwindSelf"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
