local L0_0, L1_1
L0_0 = true
DoesntBreakShields = L0_0
L0_0 = "ASSETS/Characters/Ashe/HUD/Icons2D/Ashe_Q_active.dds"
BuffTextureName = L0_0
L0_0 = "AsheQAttackNoOnHit"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
