local L0_0, L1_1
L0_0 = false
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Kled/HUD/Icons2D/Kled_P_Cooldown.dds"
BuffTextureName = L0_0
L0_0 = "KledPassiveCooldown"
BuffName = L0_0
L0_0 = true
IsDamagingSpell = L0_0
