local L0_0, L1_1
L0_0 = "ASSETS/Characters/Pantheon/HUD/Icons2D/Pantheon_CD.dds"
BuffTextureName = L0_0
L0_0 = "PantheonEPassive"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
