local L0_0
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = true
DoesntBreakShields = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = true
CastingBreaksStealth = L0_0
L0_0 = "ASSETS/Characters/Lulu/HUD/Icons2D/Lulu_CommandPix.dds"
BuffTextureName = L0_0
L0_0 = "LuluEShield"
BuffName = L0_0
L0_0 = 3
OnPreDamagePriority = L0_0
L0_0 = {"luluSkin04", "LuluSkin05"}
SpellFXOverrideSkins = L0_0
L0_0 = false
IsDamagingSpell = L0_0
L0_0 = true
DoOnPreDamageInExpirationOrder = L0_0
