local L0_0, L1_1
L0_0 = false
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Elise/HUD/Icons2D/EliseSpiderW.dds"
BuffTextureName = L0_0
L0_0 = "BuffEliseSkitter"
BuffName = L0_0
L0_0 = "r:Elise_Spiderling_W_buf"
AutoBuffActivateEffect = L0_0
L0_0 = "C_BUFFBONE_GLB_LAYOUT_LOC"
AutoBuffActivateAttachBoneName = L0_0
