local L0_0, L1_1
L0_0 = "ASSETS/Characters/Tryndamere/HUD/Icons2D/Tryndamere_W.dds"
BuffTextureName = L0_0
L0_0 = "TryndamereWSlow"
BuffName = L0_0
L0_0 = "GLOBAL_SLOW.TROY"
AutoBuffActivateEffect = L0_0
L0_0 = "r:Tryndamere_W_Buf_Chicken_01"
AutoBuffActivateEffect2 = L0_0
L0_0 = "C_BUFFBONE_GLB_HEAD_LOC"
AutoBuffActivateAttachBoneName2 = L0_0
L0_0 = "game_floatingtext_Slowed"
PopupMessage1 = L0_0
