local L1_0
function L1_0()
  CreateChildTurret("Turret_T1_R_03", "OrderTurretNormal", TEAM_ORDER, 3, 0)
  CreateChildTurret("Turret_T1_R_02", "OrderTurretNormal2", TEAM_ORDER, 2, 0)
  CreateChildTurret("Turret_T1_C_07", "OrderTurretDragon", TEAM_ORDER, 1, 0)
  CreateChildTurret("Turret_T2_R_03", "ChaosTurretWorm", TEAM_CHAOS, 3, 0)
  CreateChildTurret("Turret_T2_R_02", "ChaosTurretWorm2", TEAM_CHAOS, 2, 0)
  CreateChildTurret("Turret_T2_R_01", "ChaosTurretGiant", TEAM_CHAOS, 1, 0)
  CreateChildTurret("Turret_T1_C_05", "OrderTurretNormal", TEAM_ORDER, 3, 1)
  CreateChildTurret("Turret_T1_C_04", "OrderTurretNormal2", TEAM_ORDER, 2, 1)
  CreateChildTurret("Turret_T1_C_03", "OrderTurretDragon", TEAM_ORDER, 1, 1)
  CreateChildTurret("Turret_T1_C_01", "OrderTurretAngel", TEAM_ORDER, 5, 1)
  CreateChildTurret("Turret_T1_C_02", "OrderTurretAngel", TEAM_ORDER, 4, 1)
  CreateChildTurret("Turret_T2_C_05", "ChaosTurretWorm", TEAM_CHAOS, 3, 1)
  CreateChildTurret("Turret_T2_C_04", "ChaosTurretWorm2", TEAM_CHAOS, 2, 1)
  CreateChildTurret("Turret_T2_C_03", "ChaosTurretGiant", TEAM_CHAOS, 1, 1)
  CreateChildTurret("Turret_T2_C_01", "ChaosTurretNormal", TEAM_CHAOS, 5, 1)
  CreateChildTurret("Turret_T2_C_02", "ChaosTurretNormal", TEAM_CHAOS, 4, 1)
  CreateChildTurret("Turret_OrderTurretShrine", "OrderTurretShrine", TEAM_ORDER, 0, 1)
  CreateChildTurret("Turret_ChaosTurretShrine", "ChaosTurretShrine", TEAM_CHAOS, 0, 1)
  CreateChildTurret("Turret_T1_L_03", "OrderTurretNormal", TEAM_ORDER, 3, 2)
  CreateChildTurret("Turret_T1_L_02", "OrderTurretNormal2", TEAM_ORDER, 2, 2)
  CreateChildTurret("Turret_T1_C_06", "OrderTurretDragon", TEAM_ORDER, 1, 2)
  CreateChildTurret("Turret_T2_L_03", "ChaosTurretWorm", TEAM_CHAOS, 3, 2)
  CreateChildTurret("Turret_T2_L_02", "ChaosTurretWorm2", TEAM_CHAOS, 2, 2)
  CreateChildTurret("Turret_T2_L_01", "ChaosTurretGiant", TEAM_CHAOS, 1, 2)
end
CreateLevelProps = L1_0
