local L0_0, L1_1
L0_0 = false
NotSingleTargetSpell = L0_0
L0_0 = true
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/TFT_Lissandra/HUD/Icons2D/TFT_Lissandra_R.dds"
BuffTextureName = L0_0
L0_0 = "TFT_LissandraRSlow"
BuffName = L0_0
L0_0 = 1
SpellDamageRatio = L0_0
L0_0 = "game_floatingtext_Slowed"
PopupMessage1 = L0_0
L0_0 = true
IsDamagingSpell = L0_0
