local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = true
CastingBreaksStealth = L0_0
L0_0 = "ASSETS/Characters/Neeko/HUD/Icons2D/Neeko_W_Passive_CD.dds"
BuffTextureName = L0_0
L0_0 = "NeekoWPassiveCounter"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
