local L0_0, L1_1
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = false
CastingBreaksStealth = L0_0
L0_0 = "ASSETS/Characters/Neeko/HUD/Icons2D/Neeko_R.dds"
BuffTextureName = L0_0
L0_0 = "NeekoRShield"
BuffName = L0_0
L0_0 = false
IsDamagingSpell = L0_0
