local L0_0, L1_1
L0_0 = "ASSETS/Characters/TFT_Fizz/HUD/Icons2D/TFT_Fizz_R.dds"
BuffTextureName = L0_0
L0_0 = "TFT_FizzRCling"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
