local L0_0, L1_1
L0_0 = false
NotSingleTargetSpell = L0_0
L0_0 = "SwainW"
BuffName = L0_0
L0_0 = "global_Watched.troy"
AutoBuffActivateEffect = L0_0
L0_0 = "C_BUFFBONE_GLB_HEAD_LOC"
AutoBuffActivateAttachBoneName = L0_0
L0_0 = true
TriggersSpellCasts = L0_0
