local L0_0, L1_1
L0_0 = "Minotaur_TriumphantRoar.dds"
BuffTextureName = L0_0
L0_0 = "Pacified"
BuffName = L0_0
L0_0 = "LOC_Stun.troy"
AutoBuffActivateEffect = L0_0
L0_0 = "C_BUFFBONE_GLB_CENTER_LOC"
AutoBuffActivateAttachBoneName = L0_0
