local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntBreakShields = L0_0
L0_0 = true
DoesntTriggerSpellCasts = L0_0
L0_0 = true
CastingBreaksStealth = L0_0
L0_0 = "ASSETS/Characters/Udyr/HUD/Icons2D/Udyr_TigerStance.dds"
BuffTextureName = L0_0
L0_0 = "UdyrTigerPunchBleed"
BuffName = L0_0
L0_0 = true
IsDeathRecapSource = L0_0
L0_0 = true
IsDamagingSpell = L0_0
