local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Leona/HUD/Icons2D/LeonaShieldOfDaybreak.dds"
BuffTextureName = L0_0
L0_0 = "LeonaShieldOfDaybreak"
BuffName = L0_0
