local L0_0, L1_1
L0_0 = false
NotSingleTargetSpell = L0_0
L0_0 = "ASSETS/Characters/Swain/HUD/Icons2D/Swain_R.dds"
BuffTextureName = L0_0
L0_0 = "SwainRSoulBurn"
BuffName = L0_0
L0_0 = true
TriggersSpellCasts = L0_0
