local L0_0, L1_1
L0_0 = "ASSETS/Characters/Nautilus/HUD/Icons2D/Nautilus_StaggeringBlow.dds"
BuffTextureName = L0_0
L0_0 = "NautilusPassiveRoot"
BuffName = L0_0
L0_0 = "game_floatingtext_Snared"
PopupMessage1 = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
