local L0_0, L1_1
L0_0 = false
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Ryze/HUD/Icons2D/Ryze_W.dds"
BuffTextureName = L0_0
L0_0 = "RyzeW"
BuffName = L0_0
L0_0 = "game_floatingtext_Slowed"
PopupMessage1 = L0_0
L0_0 = true
IsDamagingSpell = L0_0
