local L0_0, L1_1
L0_0 = "Ahri_SpiritRush.dds"
BuffTextureName = L0_0
L0_0 = "AhriTumble"
BuffName = L0_0
L0_0 = "maokai_sapling_activated_indicator.troy"
AutoBuffActivateEffect = L0_0
L0_0 = "C_BUFFBONE_GLB_CHEST_LOC"
AutoBuffActivateAttachBoneName = L0_0
