local L0_0, L1_1
L0_0 = "ASSETS/Characters/Heimerdinger/HUD/Icons2D/Heimerdinger_TechmaturgicalRepairBots.dds"
BuffTextureName = L0_0
L0_0 = "TechmaturgicalIcon"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
