local L0_0, L1_1
L0_0 = false
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Spells/Icons2D/Wolfman_SeverArmor.dds"
BuffTextureName = L0_0
L0_0 = true
IsDamagingSpell = L0_0
L0_0 = true
TriggersSpellCasts = L0_0
