local L0_0, L1_1
L0_0 = true
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Darius/HUD/Icons2D/Darius_PassiveBuff.dds"
BuffTextureName = L0_0
L0_0 = "DariusHemoMax"
BuffName = L0_0
L0_0 = true
IsDeathRecapSource = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
