local L0_0, L1_1
L0_0 = true
DoesntBreakShields = L0_0
L0_0 = true
DoesntTriggerSpellCasts = L0_0
L0_0 = true
CastingBreaksStealth = L0_0
L0_0 = "SummonerIgnite.dds"
BuffTextureName = L0_0
L0_0 = "SummonerIgnite"
BuffName = L0_0
L0_0 = "GLOBAL_watched.troy"
AutoBuffActivateEffect = L0_0
L0_0 = "C_BUFFBONE_GLB_HEAD_LOC"
AutoBuffActivateAttachBoneName = L0_0
