local L0_0, L1_1
L0_0 = false
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/MasterYi/HUD/Icons2D/MasterYi_E1.dds"
BuffTextureName = L0_0
L0_0 = "WujuStyleSuperCharged"
BuffName = L0_0
