local L0_0, L1_1
L0_0 = "ASSETS/Characters/TwistedFate/HUD/Icons2D/Destiny_OldSchool.dds"
BuffTextureName = L0_0
L0_0 = "TwistedFateClassicDestiny"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
