local L0_0, L1_1
L0_0 = "ASSETS/Characters/Quinn/HUD/Icons2D/Quinn_W.dds"
BuffTextureName = L0_0
L0_0 = "QuinnWVision"
BuffName = L0_0
L0_0 = "global_Watched.troy"
AutoBuffActivateEffect = L0_0
L0_0 = "C_BUFFBONE_GLB_HEAD_LOC"
AutoBuffActivateAttachBoneName = L0_0
