local L0_0, L1_1
L0_0 = "ASSETS/Characters/TFT_Kassadin/HUD/Icons2D/TFT_Kassadin_Passive.dds"
BuffTextureName = L0_0
L0_0 = "TFT_Kassadin_VoidStone"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
