local L0_0, L1_1
L0_0 = false
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntBreakShields = L0_0
L0_0 = true
DoesntTriggerSpellCasts = L0_0
L0_0 = true
CastingBreaksStealth = L0_0
L0_0 = 6
ChannelDuration = L0_0
L0_0 = "ASSETS/Characters/Fiddlesticks/HUD/Icons2D/Fiddlesticks_ConjureScarecrow.dds"
BuffTextureName = L0_0
L0_0 = "Drain"
BuffName = L0_0
L0_0 = false
IsDamagingSpell = L0_0
