local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = true
DoesntBreakShields = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = false
CastingBreaksStealth = L0_0
L0_0 = "ASSETS/Characters/Evelynn/HUD/Icons2D/Evelynn_Q1.dds"
BuffTextureName = L0_0
L0_0 = "EvelynnQDebuff"
BuffName = L0_0
