local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = true
CastingBreaksStealth = L0_0
L0_0 = "ASSETS/Characters/Evelynn/HUD/Icons2D/Evelynn_E_passive.dds"
BuffTextureName = L0_0
L0_0 = "EvelynnEHaste"
BuffName = L0_0
L0_0 = true
NonDispellable = L0_0
