local L0_0, L1_1
L0_0 = "ASSETS/Characters/Volibear/HUD/Icons2D/VolibearPassiveGray.dds"
BuffTextureName = L0_0
L0_0 = "VolibearPassiveCD"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
