local L0_0, L1_1
L0_0 = "ASSETS/Characters/Maokai/HUD/Icons2D/Maokai_PassiveReady.dds"
BuffTextureName = L0_0
L0_0 = "r:Maokai_P_cas"
AutoBuffActivateEffect = L0_0
L0_0 = "L_BUFFBONE_GLB_HAND_LOC"
AutoBuffActivateAttachBoneName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
