local L0_0, L1_1
L0_0 = "ASSETS/Characters/Soraka/HUD/Icons2D/Soraka_E.dds"
BuffTextureName = L0_0
L0_0 = "SorakaEPacify"
BuffName = L0_0
L0_0 = "LOC_Silence.troy"
AutoBuffActivateEffect = L0_0
L0_0 = "C_BUFFBONE_GLB_HEAD_LOC"
AutoBuffActivateAttachBoneName = L0_0
L0_0 = "game_floatingtext_Silenced"
PopupMessage1 = L0_0
