local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntBreakShields = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = true
CastingBreaksStealth = L0_0
L0_0 = "ASSETS/Characters/Nautilus/HUD/Icons2D/Nautilus_GrandLine.dds"
BuffTextureName = L0_0
L0_0 = "NautilusMinorKnockUp"
BuffName = L0_0
L0_0 = "game_floatingtext_Knockup"
PopupMessage1 = L0_0
L0_0 = true
IsDamagingSpell = L0_0
