local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = true
DoesntBreakShields = L0_0
L0_0 = true
DoesntTriggerSpellCasts = L0_0
L0_0 = false
CastingBreaksStealth = L0_0
L0_0 = "ASSETS/Characters/Udyr/HUD/Icons2D/Udyr_MonkeysAgility.dds"
BuffTextureName = L0_0
L0_0 = "UdyrMonkeyAgilityBuff"
BuffName = L0_0
L0_0 = false
IsDamagingSpell = L0_0
