local L0_0, L1_1
L0_0 = false
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "OdinMinionTaunt"
BuffName = L0_0
L0_0 = "odin_minion_tower_buf.troy"
AutoBuffActivateEffect = L0_0
