local L0_0, L1_1
L0_0 = false
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Zilean/HUD/Icons2D/Zilean_E.dds"
BuffTextureName = L0_0
L0_0 = "TimeWarp"
BuffName = L0_0
L0_0 = "Global_Haste.troy"
AutoBuffActivateEffect2 = L0_0
