local L0_0, L1_1
L0_0 = false
NotSingleTargetSpell = L0_0
L0_0 = False
DoesntBreakShields = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Vayne/HUD/Icons2D/Vayne_Condemn.dds"
BuffTextureName = L0_0
L0_0 = "VayneCondemn"
BuffName = L0_0
L0_0 = true
IsDamagingSpell = L0_0
L0_0 = true
TriggersSpellCasts = L0_0
