local L0_0, L1_1
function L0_0()
  PreloadSpell("Odyssey_PlayerBuff")
  PreloadCharacterWithSkinID("VoidGate", 0)
  PreloadCharacterWithSkinID("NPC_KogMaw", 0)
  PreloadCharacterWithSkinID("NPC_KogMaw", 1)
  PreloadCharacterWithSkinID("NPC_KhaZix", 0)
  PreloadCharacterWithSkinID("NPC_VelKoz", 0)
  PreloadCharacterWithSkinID("NPC_VelKoz", 1)
  PreloadCharacterWithSkinID("NPC_Skarner", 1)
  PreloadCharacterWithSkinID("NPC_Skarner", 0)
  PreloadCharacterWithSkinID("NPC_GROMP", 0)
  PreloadCharacterWithSkinID("NPC_GROMP", 1)
  PreloadCharacterWithSkinID("NPC_GROMP", 2)
  PreloadCharacterWithSkinID("NPC_MiniTurtle", 0)
  PreloadCharacterWithSkinID("NPC_RockSpawn", 0)
  PreloadCharacterWithSkinID("NPC_Red", 1)
  PreloadCharacterWithSkinID("NPC_Red", 2)
  PreloadCharacterWithSkinID("NPC_Red", 4)
  PreloadCharacterWithSkinID("NPC_Red", 3)
  PreloadCharacterWithSkinID("NPC_Blue", 0)
  PreloadCharacterWithSkinID("NPC_Blue", 1)
  PreloadCharacterWithSkinID("NPC_LootBug", 0)
  PreloadCharacterWithSkinID("NPC_LootBug", 1)
  PreloadCharacterWithSkinID("NPC_LootBug", 2)
  PreloadCharacterWithSkinID("NPC_LootBug", 3)
  PreloadCharacterWithSkinID("NPC_LootBug", 4)
  PreloadCharacterWithSkinID("NPC_LootBug", 5)
  PreloadCharacterWithSkinID("Kayn", 2)
  PreloadCharacterWithSkinID("NPC_Hazard_BeamCrystal", 0)
  PreloadCharacterWithSkinID("NPC_Hazard_BeamCrystal", 1)
  PreloadCharacterWithSkinID("NPC_Hazard_BeamCrystal_BeamTarget", 0)
  PreloadCharacterWithSkinID("NPC_Hazard_BubbleGeyser", 0)
  PreloadCharacterWithSkinID("NPC_Hazard_Destructible_1", 0)
  PreloadCharacterWithSkinID("NPC_Hazard_OraStorm", 0)
  PreloadCharacterWithSkinID("NPC_Hazard_Volcano", 0)
  PreloadCharacterWithSkinID("NPC_Objective_OraCrate", 0)
  PreloadCharacterWithSkinID("Odyssey_OraBot", 0)
  PreloadCharacterWithSkinID("Odyssey_OraCloud", 0)
  PreloadCharacterWithSkinID("Odyssey_OraPillar", 0)
end
OnInitClient = L0_0
function L0_0()
  ApplyPersistentBuffToAllChampions("Odyssey_PlayerBuff", false)
end
OnInitServer = L0_0
