local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Nocturne/HUD/Icons2D/Nocturne_Paranoia.dds"
BuffTextureName = L0_0
L0_0 = "NocturneParanoiaTarget"
BuffName = L0_0
L0_0 = "DeathsCaress_buf.troy"
AutoBuffActivateEvent = L0_0
