local L0_0, L1_1
L0_0 = "ASSETS/Characters/Kindred/HUD/Textures/Kindred_Success.dds"
BuffTextureName = L0_0
L0_0 = "KindredHitListSuccessTracker0"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
