local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = true
DoesntTriggerSpellCasts = L0_0
L0_0 = true
CastingBreaksStealth = L0_0
L0_0 = "ASSETS/Spells/Icons2D/Summoner_teleport.dds"
BuffTextureName = L0_0
L0_0 = "Teleport"
BuffName = L0_0
