local L0_0, L1_1
L0_0 = "ASSETS/Characters/Amumu/HUD/Icons2D/Amumu_Passive.dds"
BuffTextureName = L0_0
L0_0 = "CursedTouchMarker"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
