local L0_0, L1_1
L0_0 = "ASSETS/Characters/MasterYi/HUD/Icons2D/MasterYi_Passive1.dds"
BuffTextureName = L0_0
L0_0 = "MasterYiPassive"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
