local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Blitzcrank/HUD/Icons2D/Blitzcrank_PowerFist.dds"
BuffTextureName = L0_0
L0_0 = "PowerFist"
BuffName = L0_0
L0_0 = true
IsDeathRecapSource = L0_0
