local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = true
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Hecarim/HUD/Icons2D/Hecarim_Warpath.dds"
BuffTextureName = L0_0
L0_0 = "HecarimPassive"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
IsDamagingSpell = L0_0
