local L0_0, L1_1
L0_0 = "ASSETS/Characters/Vladimir/HUD/Icons2D/Vladimir_BloodGorged.dds"
BuffTextureName = L0_0
L0_0 = "VladimirBloodGorged"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
