local L0_0, L1_1
L0_0 = "Nidalee_R2.dds"
BuffTextureName = L0_0
L0_0 = "NidaleeCougarScent"
BuffName = L0_0
L0_0 = "global_Watched.troy"
AutoBuffActivateEffect = L0_0
L0_0 = "C_BUFFBONE_GLB_HEAD_LOC"
AutoBuffActivateAttachBoneName = L0_0
