local L0_0, L1_1
L0_0 = "Summoner_haste.dds"
BuffTextureName = L0_0
L0_0 = "ItemPhageSpeed"
BuffName = L0_0
L0_0 = "Boots_Deathmarch.troy"
AutoBuffActivateEffect = L0_0
L0_0 = "Global_Haste.troy"
AutoBuffActivateEffect2 = L0_0
