local L0_0, L1_1
L0_0 = "Ashe_Q_Debuff.dds"
BuffTextureName = L0_0
L0_0 = "EnchantedCrystalArrowSlow"
BuffName = L0_0
L0_0 = "Global_Freeze.troy"
AutoBuffActivateEffect = L0_0
L0_0 = "game_floatingtext_Slowed"
PopupMessage1 = L0_0
