local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = true
CastingBreaksStealth = L0_0
L0_0 = "ASSETS/Characters/Rengar/HUD/Icons2D/RengarQ.dds"
BuffTextureName = L0_0
L0_0 = "RengarQBuff"
BuffName = L0_0
L0_0 = true
IsDeathRecapSource = L0_0
