local L0_0, L1_1
L0_0 = "ASSETS/Characters/Poppy/HUD/Icons2D/Poppy_Passive.dds"
BuffTextureName = L0_0
L0_0 = "PoppyPassive"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
