local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = true
DoesntTriggerSpellCasts = L0_0
L0_0 = "2048_Ichor_of_Illumination.dds"
BuffTextureName = L0_0
L0_0 = "ElixirOfIllumination"
BuffName = L0_0
L0_0 = "PotionofBrilliance_itm.troy"
AutoBuffActivateEffect = L0_0
L0_0 = "C_Buffbone_Glb_Center_Loc"
AutoBuffActivateAttachBoneName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
