local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Thresh/HUD/Icons2D/Thresh_Q.dds"
BuffTextureName = L0_0
L0_0 = "game_floatingtext_Stunned"
PopupMessage1 = L0_0
L0_0 = true
IsDamagingSpell = L0_0
