local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = true
DoesntBreakShields = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = true
CastingBreaksStealth = L0_0
L0_0 = "ASSETS/Characters/Gangplank/HUD/Icons2D/Gangplank_Coin.dds"
BuffTextureName = L0_0
L0_0 = "GangplankBilgewaterToken"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = false
IsDamagingSpell = L0_0
