local L0_0, L1_1
L0_0 = true
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Lucian/HUD/Icons2D/Lucian_R.dds"
BuffTextureName = L0_0
L0_0 = "LucianR"
BuffName = L0_0
L0_0 = "Lucian_R_self.troy"
AutoBuffActivateEffect = L0_0
L0_0 = 4
SpellToggleSlot = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
