local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = true
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/AurelionSol/HUD/Icons2D/AurelionSol_R.dds"
BuffTextureName = L0_0
L0_0 = "AurelionSolRSlow"
BuffName = L0_0
