local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "Regeneration_Sigil.dds"
BuffTextureName = L0_0
L0_0 = "ItemMonsterRegen"
BuffName = L0_0
L0_0 = "SRU_JungleBuff_HealthRegen.troy"
AutoBuffActivateEffect = L0_0
