local L0_0, L1_1
L0_0 = false
NotSingleTargetSpell = L0_0
L0_0 = true
DoesntBreakShields = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Gnar/HUD/Icons2D/Gnar_E.dds"
BuffTextureName = L0_0
L0_0 = "GnarEAttackSpeed"
BuffName = L0_0
