local L0_0, L1_1
L0_0 = "ASSETS/Characters/Renekton/HUD/Icons2D/Renekton_Passive.dds"
BuffTextureName = L0_0
L0_0 = "RenektonPredator"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
