local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Rammus/HUD/Icons2D/Armordillo_ShellBash.dds"
BuffTextureName = L0_0
L0_0 = "DefensiveBallCurl"
BuffName = L0_0
L0_0 = 2
SpellToggleSlot = L0_0
