local L0_0, L1_1
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = true
CastingBreaksStealth = L0_0
L0_0 = "L_Hand"
AutoBuffActivateAttachBoneName = L0_0
L0_0 = "R_Hand"
AutoBuffActivateAttachBoneName2 = L0_0
