local L0_0, L1_1
L0_0 = "TT_Spider_Icon.dds"
BuffTextureName = L0_0
L0_0 = "TTBossBuff"
BuffName = L0_0
L0_0 = "TT_spiderboss_buff.troy"
AutoBuffActivateEffect = L0_0
L0_0 = true
NonDispellable = L0_0
