local L0_0, L1_1
L0_0 = "ASSETS/Characters/Leblanc/HUD/Icons2D/LeblancDisplacementReturn.dds"
BuffTextureName = L0_0
L0_0 = "LeblancDisplacement"
BuffName = L0_0
L0_0 = 2
SpellToggleSlot = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
