local L0_0, L1_1
L0_0 = "Dragon_Debuff.dds"
BuffTextureName = L0_0
L0_0 = "DragonBurning"
BuffName = L0_0
L0_0 = "SRU_dragon_BA1_tar.troy"
AutoBuffActivateEffect = L0_0
L0_0 = true
IsDeathRecapSource = L0_0
L0_0 = "game_floatingtext_Slowed"
PopupMessage1 = L0_0
