local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Graves/HUD/Icons2D/GravesPShell1.dds"
BuffTextureName = L0_0
L0_0 = "GravesBasicAttackAmmo1"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
