local L0_0, L1_1
L0_0 = "Regeneration_Sigil.dds"
BuffTextureName = L0_0
L0_0 = "RegenerationAura"
BuffName = L0_0
L0_0 = "regen_rune_new_buf.troy"
AutoBuffActivateEffect = L0_0
L0_0 = "Buffbone_Glb_Ground_Loc"
AutoBuffActivateAttachBoneName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
Nondispellable = L0_0
