local L0_0, L1_1
L0_0 = false
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Elise/HUD/Icons2D/EliseSpiderQ.dds"
BuffTextureName = L0_0
L0_0 = "EliseSpiderQ"
BuffName = L0_0
L0_0 = "r:Global_Poison_BV2"
AutoBuffActivateEffect2 = L0_0
L0_0 = "C_BUFFBONE_GLB_HEAD_LOC"
AutoBuffActivateAttachBoneName2 = L0_0
L0_0 = true
IsDamagingSpell = L0_0
L0_0 = true
TriggersSpellCasts = L0_0
