local L0_0, L1_1
L0_0 = true
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Nami/HUD/Icons2D/Janna_Tailwind.dds"
BuffTextureName = L0_0
L0_0 = "NamiPassive"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
