local L0_0, L1_1
L0_0 = "ItemWrigglesLanternCounter.dds"
BuffTextureName = L0_0
L0_0 = "ItemMadredsRazorCounter"
BuffName = L0_0
L0_0 = true
PersistsThroughDeath = L0_0
L0_0 = true
NonDispellable = L0_0
