local L0_0, L1_1
L0_0 = "NightmareBotSpiritSinged.dds"
BuffTextureName = L0_0
L0_0 = "Poisoned"
BuffName = L0_0
L0_0 = "Global_Poison.troy"
AutoBuffActivateEffect = L0_0
L0_0 = "C_BUFFBONE_GLB_HEAD_LOC"
AutoBuffActivateAttachBoneName = L0_0
