local L0_0, L1_1
L0_0 = true
NotSingleTargetSpell = L0_0
L0_0 = false
DoesntTriggerSpellCasts = L0_0
L0_0 = "ASSETS/Characters/Sivir/HUD/Icons2D/Sivir_W.dds"
BuffTextureName = L0_0
L0_0 = "SivirWMarker"
BuffName = L0_0
L0_0 = "r:Sivir_W_Buff"
AutoBuffActivateEffect = L0_0
L0_0 = "Buffbone_Cstm_Weapon_1"
AutoBuffActivateAttachBoneName = L0_0
L0_0 = true
NonDispellable = L0_0
