local L0_0, L1_1
L0_0 = "ASSETS/Characters/Kalista/HUD/Icons2D/Kalista_R.dds"
BuffTextureName = L0_0
L0_0 = "KalistaRInvuln"
BuffName = L0_0
L0_0 = "r:Kalista_R_Zhonyas_Sound"
AutoBuffActivateEffect4 = L0_0
L0_0 = "C_Buffbone_Glb_Head_Loc"
AutoBuffActivateAttachBoneName4 = L0_0
